# Generated by Django 4.2 on 2023-04-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='LotusPaga_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.moedapaga'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='Sakuras_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.moedapadrao'),
        ),
        migrations.AlterField(
            model_name='moedapadrao',
            name='Sakuras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='moedapaga',
            name='Lotus_Gold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IMG_Perfil',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao_perfil',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID_USER_PERFIL'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contas.perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
