# Generated by Django 4.2 on 2023-04-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiacarta',
            name='afinidade',
        ),
        migrations.RemoveField(
            model_name='copiacarta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='copiacarta',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='copiacarta',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='copiacarta',
            name='level',
        ),
        migrations.RemoveField(
            model_name='copiacarta',
            name='nome',
        ),
        migrations.AlterField(
            model_name='copiacarta',
            name='idcard',
            field=models.ForeignKey(limit_choices_to={'imagem': '', 'nome': ''}, on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='copiacarta',
            name='valor',
            field=models.ForeignKey(limit_choices_to={'afinidade': '', 'exp': '', 'level': '', 'valor': ''}, on_delete=django.db.models.deletion.CASCADE, to='contas.categoria'),
        ),
    ]
