# Generated by Django 4.2 on 2023-04-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='sakuras_user',
            new_name='Lotus_user',
        ),
        migrations.RenameField(
            model_name='moedapadrao',
            old_name='Sakuras',
            new_name='Lotus',
        ),
        migrations.CreateModel(
            name='CampoDeTreinamento',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_CAMPO_DE_TREINAMENTO')),
                ('Limite', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tempo', models.DateTimeField(auto_now_add=True)),
                ('CartaParaUpar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta')),
            ],
        ),
    ]
