# Generated by Django 4.1.7 on 2023-03-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=400)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('afinidade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('exp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.categoria')),
            ],
        ),
    ]
