# Generated by Django 4.2 on 2023-05-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckuser',
            name='NomeDeckUser',
        ),
        migrations.RemoveField(
            model_name='deckuser',
            name='cartasDeckUser',
        ),
        migrations.AddField(
            model_name='deckuser',
            name='cartasDeckUser',
            field=models.ManyToManyField(related_name='decks', to='contas.carta'),
        ),
    ]
