# Generated by Django 4.2 on 2023-04-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_carteira_lotuspaga_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_User')),
                ('nomeUser', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=100)),
                ('senha2', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='bat_log',
            name='ID_USER_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='ID_USER_carteira',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='deckuser',
            name='IDUserDeck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='event_user',
            name='ID_USER_evt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='invent',
            name='ID_USER_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='inventario_carta',
            name='ID_USER_INV_CARD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='mercadoglobal',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user', verbose_name='ID_USER_MARKET'),
        ),
        migrations.AlterField(
            model_name='mercadoglobalplayer',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user', verbose_name='ID_USER_MARKET'),
        ),
        migrations.AlterField(
            model_name='minigame_user',
            name='ID_USER_minig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contas.user', verbose_name='ID_USER_PERFIL'),
        ),
        migrations.AlterField(
            model_name='sistemadetroca',
            name='ID_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user'),
        ),
    ]
