# Generated by Django 4.2 on 2023-05-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_deckuser_nomedeckuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('atributo_base', models.IntegerField()),
                ('vida', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='campodetreinamento',
            name='CartaParaUpar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='copiacarta',
            name='idcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='datesim',
            name='ID_CARD_DATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cartas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='deckuser',
            name='cartasDeckUser',
            field=models.ManyToManyField(related_name='decks', to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='invent',
            name='carta_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='inventario_carta',
            name='CARTA_INV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='lootbox_superior',
            name='ItemLootBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.AlterField(
            model_name='sistemadetroca',
            name='ID_TROCA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartas'),
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
    ]
