# Generated by Django 4.1.7 on 2023-03-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_carta_observacoes_alter_carta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nomec',
        ),
    ]
