# Generated by Django 4.2 on 2023-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_user_delete_users_alter_bat_log_id_user_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nomeUser',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha2',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IMG_Perfil',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao_perfil',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
