# Generated by Django 4.2 on 2023-10-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_cartas_alter_campodetreinamento_cartaparaupar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=500)),
                ('Anime', models.CharField(max_length=400)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.atributos')),
                ('metasCartas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.metas')),
                ('talentoCartas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.talentos')),
                ('tipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='campodetreinamento',
            name='CartaParaUpar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='copiacarta',
            name='idcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='datesim',
            name='ID_CARD_DATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cartas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='deckuser',
            name='cartasDeckUser',
            field=models.ManyToManyField(related_name='decks', to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='invent',
            name='carta_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='inventario_carta',
            name='CARTA_INV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='lootbox_superior',
            name='ItemLootBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.AlterField(
            model_name='sistemadetroca',
            name='ID_TROCA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.carta'),
        ),
        migrations.DeleteModel(
            name='Cartas',
        ),
    ]
