# Generated by Django 4.2 on 2023-04-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_batalha_eventos_minigame_user_minigame_user_invent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
